################################# Default configuration ###################
baseURL = "//www.sepufc.com"
title = "SEP 2020 | Semana de Engenharia de Produção UFC"
description = "17° edição da Semana de Engenharia de Produção da Universidade Federal do Ceará"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
DefaultContentLanguage = "pt"
# disable language
disableLanguages = ["en","fr"]


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################

# main menu
[[menu.main]]
name = "Sobre"
URL = "about"
weight = 1

[[menu.main]]
name = "Programação"
URL = "project"
weight = 2


[[menu.main]]
name = "Inscreva-se"
URL = "pricing"
weight = 3

[[menu.main]]
name = "Perguntas Frequentes"
URL = "faq"
weight = 4

[[menu.main]]
name = "Mais"
URL = ""
weight = 5
hasChildren = true

	[[menu.main]]
  	parent = "Mais"
  	name = "Contato"
  	URL = "contact"

	[[menu.main]]
  	parent = "Mais"
  	name = "Staff"
  	URL = "staff"




#################### default parameters ################################
[params]
logo = "images/logo4.png"
# Meta data
description = "This is meta description"
author = "PET Produção"
# Contact Information
phone = "994106831 | 987414628"
email = "sep@ufc.br"
location = "Campus do Pici | Universidade Federal do Ceará"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

  
############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "sep.ufc@gmail.com"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/company/sepufc/"

[[params.social]]
icon = "ion-social-whatsapp-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "http://api.whatsapp.com/send?phone=55085994106831"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/sepufc/?igshid=1q29s3ejgy89f"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/sepufc"

################################ Portugues Language ########################
[Languages.pt]
languageName = "Pt"
languageCode = "pt-br"
contentDir = "content/portugues"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 [PET Produção](https://petprod.ufc.br) Todos os direitos reservados"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
# copyright
copyright = "Copyright &copy; 2019 [PET Produção](https://petprod.ufc.br) All Rights Reserved"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"